name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE }}
        with:
          release-type: simple
